# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimDate', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('caption', models.CharField(blank=True, max_length=34, null=True, verbose_name='内容')),
                ('filepath', models.CharField(blank=True, max_length=200, null=True, verbose_name='文件地址')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片库',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimDate', models.DateTimeField(auto_created=True)),
                ('username', models.CharField(blank=True, max_length=20, unique=True, verbose_name='登录名')),
                ('pwd', models.CharField(blank=True, max_length=34, null=True, verbose_name='密码')),
                ('salt', models.CharField(blank=True, max_length=32, null=True, verbose_name='密码盐值')),
                ('avt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.picture')),
            ],
            options={
                'verbose_name': '用户资料表',
                'verbose_name_plural': 'users',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='coverImg',
        ),
        migrations.RemoveField(
            model_name='article',
            name='innerImgs',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='img',
        ),
        migrations.AddField(
            model_name='article',
            name='imgs',
            field=models.ManyToManyField(to='core.picture'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='img',
            field=models.ManyToManyField(to='core.picture'),
        ),
    ]
