# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170316_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='dimDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
