# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170317_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='imgs',
        ),
    ]
