# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_article_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用户类型'),
        ),
    ]
