# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('groupName', models.CharField(max_length=20, verbose_name='流程组名')),
                ('orderId', models.CharField(max_length=20, verbose_name='下一个流程id号')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ManyToManyField(to='core.user')),
            ],
            options={
                'verbose_name_plural': '流程们',
                'ordering': ['id'],
                'verbose_name': '流程表',
            },
        ),
    ]
