# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='flowgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ManyToManyField(to='core.user')),
            ],
            options={
                'verbose_name': '流程组表',
                'verbose_name_plural': '流程组们',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='flow',
            name='groupName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flowgroup'),
        ),
    ]
